version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contact-center-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=contact_center
      - DB_USERNAME=contact
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - SANCTUM_STATEFUL_DOMAINS=localhost:3001
      - SESSION_DOMAIN=localhost
    depends_on:
      - db
      - redis
    ports:
      - "8080:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contact-center-frontend
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: contact-center-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: contact_center
      MYSQL_USER: contact
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:7
    container_name: contact-center-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data"

volumes:
  dbdata:
  redisdata:

